NOMBRE = ..\bin\salida
ARCHIVOS = *.cpp
FLAGS = -IC:\MinGW\bibliotecas\SDL2\include\SDL2 -LC:\MinGW\bibliotecas\SDL2\lib -w -Wl, -lmingw32 -lSDL2main -lSDL2 -lSDL2_image #-subsystem,windows

build:
	g++  $(ARCHIVOS) $(FLAGS) -o $(NOMBRE)

